export const data = [{
    "childrenNum": 1,
    "displayName": "函数",
    "displayType": "function",
    "id": "1",
    "isExpanded": true,
    "pid": "",
    children: [{
        "childrenNum": 2,
        "displayName": "参数值",
        "displayType": "",
        "id": "1.0",
        "isExpanded": true,
        "pid": "1",
        children: [{
            "childrenNum": 5,
            "displayName": "a1",
            "displayType": "struct A ",
            "id": "1.0.0",
            "isExpanded": false,
            "pid": "1.0",
            children: [{
                "childrenNum": 0,
                "displayName": "A_a",
                "displayType": "int ",
                "id": "1.0.0.0",
                "isExpanded": false,
                "pid": "1.0.0",
            }, {
                "childrenNum": 0,
                "displayName": "A_b",
                "displayType": "int ",
                "id": "1.0.0.1",
                "isExpanded": false,
                "pid": "1.0.0",
            }, {
                "childrenNum": 1,
                "displayName": "B_ptr",
                "displayType": "struct B *",
                "id": "1.0.0.2",
                "isExpanded": false,
                "pid": "1.0.0",
                children: [{
                    "childrenNum": 1,
                    "displayName": "B_ptr[0]",
                    "displayType": "struct B ",
                    "id": "1.0.0.2.0",
                    "isExpanded": false,
                    "pid": "1.0.0.2",
                    children: [{
                        "childrenNum": 22,
                        "displayName": "abc",
                        "displayType": "enum geo ",
                        "id": "1.0.0.2.0.0",
                        "isExpanded": false,
                        "pid": "1.0.0.2.0",
                        children: [{
                            "childrenNum": 0,
                            "displayName": "U_read",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.0",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_write",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.1",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_verify",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.2",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                            children: []
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_read",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.0",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_write",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.1",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_verify",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.2",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_read",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.0",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_write",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.1",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_verify",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.2",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_rea22d",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.0",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_write",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.1",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_verify",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.2",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_read1",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.0",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_write",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.1",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_verify",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.2",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_read",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.0",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_write",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.1",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_verify",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.2",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_read",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.0",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_write",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.1",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, {
                            "childrenNum": 0,
                            "displayName": "U_verify",
                            "displayType": "int ",
                            "id": "1.0.0.2.0.0.2",
                            "isExpanded": false,
                            "pid": "1.0.0.2.0.0",
                        }, ]
                    }, ]
                }, ]
            }, {
                "childrenNum": 2,
                "displayName": "弄啥",
                "displayType": "<anonymous struct> ",
                "id": "1.0.0.3",
                "isExpanded": false,
                "pid": "1.0.0",
                children: [{
                    "childrenNum": 0,
                    "displayName": "c",
                    "displayType": "int ",
                    "id": "1.0.0.3.0",
                    "isExpanded": false,
                    "pid": "1.0.0.3",
                }, {
                    "childrenNum": 0,
                    "displayName": "d",
                    "displayType": "int ",
                    "id": "1.0.0.3.1",
                    "isExpanded": false,
                    "pid": "1.0.0.3",
                }, ]
            }, {
                "childrenNum": 2,
                "displayName": "M",
                "displayType": "<anonymous union> ",
                "id": "1.0.0.4",
                "isExpanded": false,
                "pid": "1.0.0",
                children: [{
                    "childrenNum": 0,
                    "displayName": "M_a",
                    "displayType": "int ",
                    "id": "1.0.0.4.0",
                    "isExpanded": false,
                    "pid": "1.0.0.4",
                }, {
                    "childrenNum": 0,
                    "displayName": "M_b",
                    "displayType": "int ",
                    "id": "1.0.0.4.1",
                    "isExpanded": false,
                    "pid": "1.0.0.4",
                }, ]
            }, ]
        }, {
            "childrenNum": 1,
            "displayName": "b1",
            "displayType": "struct B *",
            "id": "1.0.1",
            "isExpanded": false,
            "pid": "1.0",
            children: [{
                "childrenNum": 1,
                "displayName": "b1[0]",
                "displayType": "struct B ",
                "id": "1.0.1.0",
                "isExpanded": false,
                "pid": "1.0.1",
                children: [{
                    "childrenNum": 3,
                    "displayName": "abc",
                    "displayType": "enum geo ",
                    "id": "1.0.1.0.0",
                    "isExpanded": false,
                    "pid": "1.0.1.0",
                    children: [{
                        "childrenNum": 0,
                        "displayName": "U_read",
                        "displayType": "int ",
                        "id": "1.0.1.0.0.0",
                        "isExpanded": false,
                        "pid": "1.0.1.0.0",
                    }, {
                        "childrenNum": 0,
                        "displayName": "U_write",
                        "displayType": "int ",
                        "id": "1.0.1.0.0.1",
                        "isExpanded": false,
                        "pid": "1.0.1.0.0",
                    }, ]
                }, ]
            }, ]
        }, {
            "childrenNum": 0,
            "displayName": "c1",
            "displayType": "int ",
            "id": "1.0.1.0.0.0",
            "isExpanded": false,
            "pid": "1.0.1.0.0",
        }, ]
    }]
}, ]
export const data2 = [{
    "childrenNum": 0,
    "displayName": "U_write1",
    "displayType": "int ",
    "id": "1.0.0.2.0.0.1",
    "isExpanded": false,
    "pid": "1.0.0.2.0.0",
}, {
    "childrenNum": 0,
    "displayName": "U_verify2",
    "displayType": "int ",
    "id": "1.0.0.2.0.0.2",
    "isExpanded": false,
    "pid": "1.0.0.2.0.0",
}, {
    "childrenNum": 0,
    "displayName": "U_read3",
    "displayType": "int ",
    "id": "1.0.0.2.0.0.0",
    "isExpanded": false,
    "pid": "1.0.0.2.0.0",
}, ]
export const data3 = {
    "childrenNum": 0,
    "displayName": "U_read",
    "displayType": "int ",
    "id": "1.0.1.0.0.0",
    "isExpanded": false,
    "pid": "1.0.1.0.0",
}